### PR TITLE
Fallback code for mulhi for (u)int64 for machines without int128

### PR DESCRIPTION
**Pull request by cyrilbouvier**
The code implement mulhi for 64-bit types for Simd128, Simd256 and Simd512 in the case where there is no int128 type.

The code uses `imulq` and `mulq`, so it works only on 64-bit machines.
For simd on 64-bit types, we need at least SSE4, which, if I am not mistaken, is only available on 64-bit machine, so the above limitation is harmless.

### CODE REVIEW

**Comment by P1K** [comment]
Hi Cyril,
Do you know why some of the checks are failing?
Also, tho I agree that explicitly using the 64x64->128-bit multiplier is probably the best way to do this if it is not directly exposed by the compiler, I'm wondering if it is worth the annoyance of including inline assembly?
Wouldn't it be better to do a silly sub-optimal big integer implementation instead? (As anyway this part of the code is unlikely to be executed?)
(I also have some work in progress to actually vectorize this thing, but my guess is that *maybe* it's going to be more efficient on AVX-512, and probably not on smaller vectors.)

**Comment by cyrilbouvier** [comment]
> Do you know why some of the checks are failing?

There was a bug in Givaro (that is fixed now) that prevented the compilation of fflas. I relaunch the tests, it should be ok now.

> Also, tho I agree that explicitly using the 64x64->128-bit multiplier is probably the best way to do this if it is not directly exposed by the compiler, I'm wondering if it is worth the annoyance of including inline assembly?
Wouldn't it be better to do a silly sub-optimal big integer implementation instead? (As anyway this part of the code is unlikely to be executed?)

I would be in favor of using the fastest code. But if using inline assembly in Givaro is not recommended, I could implement the mulhi with 4 multiplications (32x32->64).

Should this functionnality be available more widely in Givaro ? It could be called something like mul64x64_128, and use int128 if available and a fallback (inline assembly or big integer code) otherwise. 

> (I also have some work in progress to actually vectorize this thing, but my guess is that maybe it's going to be more efficient on AVX-512, and probably not on smaller vectors.)

We can wait for your code to be finished, so we can compare and merge only the fastest code.

**Comment by ClementPernet** [comment]
What's the status on this issue? Do we need to want for a fix before releasing v2.4.0 ?

**Comment by P1K** [comment]
I don't think that inline assembly is really worth it here, but that's a bit subjective. If we want an implementation when there's no `int128_t`, I'd vote for an ad-hoc bignum code.

**Comment by cyrilbouvier** [comment]
> What's the status on this issue? 

We are waiting to see if the computation can be vectorized. And if not if we should use inline assembly or c++ code for the fallback. 

> Do we need to want for a fix before releasing v2.4.0 ?

There is no need to merge this PR before the release, it can wait.

**Comment by P1K** [comment]
One small comment: I just stumbled upon the `_mulx_u64`  intrinsic that allows to access the 64 high bit result without resorting to inline assembly. However it requires the CPU flag BMI2, so that's doesn't really solve everything (or anything at all?)

**Comment by cyrilbouvier** [comment]
I implemented Pierre's proposition in commit 719f210.
There was already a mulhi_64 in `fflas-ffpack/utils/bit_manipulation.h`, so I added a version for `uint64_t`. These functions use (u)int128_t when available, or a fallback using bignum computation. Then I used these two functions in Simd::mulhi for (u)int64_t.

**Review by P1K — APPROVED** [review]
Thanks, LGTM
I've just added a tiny change in the new `mulhi_u64` to improve readability.
`test-simd` for this code still passes

**Pull request merged**
