### PR TITLE
Fix bug with ftrsm-mp 

### PR DESCRIPTION
**Pull request by pascalgiorgi**
fixing #29

### CODE REVIEW

**Comment by ClementPernet** [comment]
Looks good to me except the following remarks:
 * you commented out the ENABLE_ALL_CHECKINGS in test-ftrsm.C When reverting it, it triggers a bug:
```
Checking with Modular<Integer> modulo 23
terminate called after throwing an instance of 'FailureFgemmCheck'
Checking FTRSM_Lower_Left_NoTrans_Unit............Aborted
```
Is it just something not implemented in the fgemm_checker or an actual bug either in ftrsm_mp or fgemm_checker. In either case, an issue should be opened with this bug.
 * many added lines are debugging print instructions commented out. Do you want to leave them as is intentionnaly, in case further debugging is required? Otherwise, can you just remove them?

**Comment by ClementPernet** [comment]
Also can you revert the field in `test-fgemm`  ?

**Comment by pascalgiorgi** [comment]
I still need to comment out the  ENABLE_ALL_CHECKINGS since the fgemm checker is buggy.
I am preparing to post something on it soon.

**Comment by pascalgiorgi** [comment]
I did not touch the test-fgemm file, what do you mean by revert the field in test-fgemm ?

**Comment by ClementPernet** [comment]
I meant in `test-fgemm-check.C`. Sorry for the confusion.

**Comment by pascalgiorgi** [comment]
Field has been reverted.

**Comment by ClementPernet** [comment]
Thanks. And what about my second point (comments of prints) ?

**Comment by pascalgiorgi** [comment]
I still need some debugging informations for #67, I will clean them up afterward.

**Pull request merged**
