### PR TITLE
Improve parallelisation of fgemm with RNS. Write a benchmark binary

### PR DESCRIPTION
**Pull request by cyrilbouvier**
Add the possibility to choose how to do parallelisation for fgemm with RNS: the caller of the fgemm function can specify how to perform the parallelisation of the loop on the moduli and of fgemm independently.
For this I create a `ParSeqHelper::Compose` that is a pair of two ParSeqHelper (either Sequential or Parallel).

### CODE REVIEW

**Comment by jgdumas** [comment]
Any test with parallelism gives me a seg fault :
> ./benchmarks/benchmark-fgemm-rns -p 1
Erreur de segmentation (core dumped)

**Comment by jgdumas** [comment]
There exist fzero and frand in fflas_level1.inl, why not using those ?

**Comment by jgdumas** [comment]
sometimes FAILED with multiple threads, at least on 2 different machines
-p 1 -t 4 is OK
'-p 1 -t 6' or '-p 1 -t 8' : FAILED

**Comment by cyrilbouvier** [comment]
> There exist fzero and frand in fflas_level1.inl, why not using those ?

I don't know why I did not use this function. This is done in fb0d554.

> sometimes FAILED with multiple threads, at least on 2 different machines
-p 1 -t 4 is OK
'-p 1 -t 6' or '-p 1 -t 8' : FAILED

Why do you mean by FAILED ? I am not able to reproduce this behavior (all above commands return successfully). What flags are used during compilation ?

**Comment by ClementPernet** [comment]
I checked and the benchmark runs smoothly on a 32 cores machine. @jgdumas FAILED problem seems to be unrelated to the PR but to a bug with OpenBLAS on skx (to be solved in another issue).

**Comment by ClementPernet** [comment]
LGTM

**Pull request merged**
