### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by NicsTr**
Add some examples (requested by #177)

### CODE REVIEW

**Comment by ClementPernet** [comment]
Looks good except 2 minor things:
- one should rather use ModularBalanced<double> as it performs faster
- several bugs in the dimensions and strides in solve.C + info=1 should be caught and print "system is inconsistent".
I did the fixes in a branch, which I had to push as I can not push to your one.
This is https://github.com/linbox-team/fflas-ffpack/tree/NicsTr-examples

**Comment by ClementPernet** [comment]
You can  
1. either merge my branch into yours and then I merge the PR, 
2. or we switch branches (ie. close this PR and create another one with the other branch and merge it).
I vote for 1.

**Comment by NicsTr** [comment]
Thanks for the review.

It should be ready to be merged now.

**Comment by ClementPernet** [comment]
LGTM

**Pull request merged**
