### PR TITLE
Checkers

### PR DESCRIPTION
**Pull request by jgdumas**
Defines a set of probabilistic checker classes.
Use Freivalds checks for fgemm, ftrsm, pluq, invert, and DumasKaltofen for charpoly.

Checks are done in two phases (init/check) in order to maximize in place computations (at most linear memory overhead).
Ideally, should be placed around all top level calls (see FGEMM, FTRSM, PLUQ, Invert, LUdivine ...)

When disabled the init/check are noop function calls (see Checker_Empty).

### CODE REVIEW

**Comment by ClementPernet** [comment]
Can one of the admins verify this patch?

**Comment by ClementPernet** [comment]
The checker code looks fine. Still I'd like to raise a few issues:
* in many places (benchmarks and tests), you sample a random matrix "by hand" with a for loop and calls to F.random. Please use frand or RandomMatrix instead (I saw that you already made a few uses of frand in this branch). 
As for the generation of random triangular matrices, we should have methodes returning them so you avoid the for bug prone loops each time you need one. Let's leave it as is for the moment, and I'll create an enhancement issue for it.
* when computing A - xId (checker_charpoly line 114), avoit testing i==j inside the for loop. Instead use the fassign routine to copy A then change the diagonal elements.
*  I understand the motivation for changing the name LUdivine-> _LUdivine and PLUQ -> _PLUQ . However, I am really not a fan of mutliplying the routine names. The whole rewrite of the fgemm routine was in part motivated by the need to remove a bunch of _fgemm or fgemm_ which made the code very hard to maintain. What about using helpers as a last argument ?

**Comment by ClementPernet** [comment]
Many of the failures reported by the CI are related to a linking problem in compiling tests/test-ftrsm-checkers.C 
Investigating it, I found commit 28616895ec673bbdb256fab55638670bce77ad4f which I strongly disagree. You should not remove the if FFLASFFPACK_PRECOMPILE then else block . It probably is the reason for this linking failure. I have no ssh access to the CI slaves for the moment to check it but will do soon.

**Comment by jgdumas** [comment]
first two points of Clément done.

**Comment by jgdumas** [comment]
OK, linking problem should be solved.
For Clément's last point about _PLUQ/_LUDivine, it is there since the high level method recursively calls itself. So there are two solutions:
1/ add the checks at every recursive level 
2/ change _PLUQ to PLUQ but add an additional template trait

**Comment by ClementPernet** [comment]
Great 
As for JG's question I would rather not do the check at each recursive level. So either use a template helper or replace all recursive calls by `_LUdivine`

Thanks for fixing all other issues. Note that eventhough the CI reports success there is still `benchmark-checkers` failing (and also `test-ftrsm` as reported in issue #29 )

**Comment by ClementPernet** [comment]
triggerCI

**Comment by ClementPernet** [comment]
test

**Comment by ClementPernet** [comment]
triggerCI

**Comment by ClementPernet** [comment]
triggerCI

**Comment by ClementPernet** [comment]
Everything's now fine. And CI says no more bugs.
Merging.

**Pull request merged**
