### PR TITLE
Fix test-simd.C

### PR DESCRIPTION
**Pull request by cyrilbouvier**
I rewrote test-simd.C and added it in tests/Makefile.am in order to add it in the test suite

I had one question: for the tests of SIMD functions on float and double, we generate random vector of real between [-MAX, MAX] with a uniform distribution. So most of the elements are very large (like 1e307 for double). But in practice we use those functions with smaller values (less than 1e27 or 1e53). Should we try to generate smaller values to match our usage of those functions or we do not care ?

This is a WIP, there are some functions that are not tested yet.

### CODE REVIEW

**Comment by P1K** [comment]
Hello Cyril,
test-simd from this branch still doesn't seem to compile for me

**Comment by cyrilbouvier** [comment]
> test-simd from this branch still doesn't seem to compile for me

Can you send the error message from the compiler ?
And what is your configuration regarding SIMD capabilities ?

**Comment by P1K** [comment]
> And what is your configuration regarding SIMD capabilities ?

If you're referring to my hardware, I tried on a machine with avx2 and on one with avx512.

> Can you send the error message from the compiler ?

I get a whole bunch of errors, similar to before the fix (so I'm mostly worried I'm not doing things properly; I basically moved onto the branch and reconfigured from scratch?). The first one (avx2 machine) is

```
test-simd.C:161:32: error: implicit instantiation of undefined template 'std::__1::array<float, 1>'
    std::array<Element, arity> scal_in;
```

And the first one (avx512) is
```
test-simd.C:334:36: error: incomplete type ‘Simd512_impl<true, true, true, 2>’ used in nested name specifier
     btest &= test_op<simd,Element> (simd::name, Scal::name, #name);
```

**Comment by cyrilbouvier** [comment]
The first error should be fixed by 7bf4619

Regarding the second error, the discussion could also be interesting for #184. For each size nnn of SIMD (with nnn = 128, 256 or 512) there is a templated structure `Simdnnn_impl` defined in `simdnnn.inl` (located in `fflas-ffpack/fflas/fflas_simd`). This structure is template by 3 bool (arithmetic type or not, integral or floating, signed or unsigned) and 1 int (corresponding to sizeof (the scalar type)).
Each file `simdnnn_type.inl` implements one specialization of this templated structure.
For nnn = 128 or 256, specialization exists for double, float, (signed and unsigned) int16, (signed and unsigned) int32 and (signed and unsigned) int64.
For nnn = 512, the specialization for (signed and unsigned) int16 is missing (is it because there is no such intrinsic functions ?).

This cause the error in the function `test<int16_t>`, because `Simd512<int16_t>` is an alias for `Simd512_impl<true, true, true, 2>` which is defined but not implemented.

There is two solutions:
1. write the specialization for `Simd512_impl<true, true, true, 2>` (if the intrinsics allow it) in a new file `simd512_int16.inl` and keep the generic code in `test-simd.C`
2. write specific code for `Simd512` in `test-simd.C` (and possibly every file that use `Simd512` with `(u)int16_t`.

As I do not have AVX512 on my machine, I could write the code but I cannot test it.

**Comment by P1K** [comment]
> The first error should be fixed by [7bf4619](https://github.com/linbox-team/fflas-ffpack/commit/7bf46195a14f9225e2725a2c43632cab5809baa5)

Yup, that works. Thanks.

Regarding AVX512, I can have a go at implementing  `simd512_int16.inl`. I was also thinking of having a look at the buggy `Simd256<uint32_t>::mulhi`, if you're (or anynone else is) not already doing that.

**Comment by cyrilbouvier** [comment]
I can look at the problem with `Simd256<uint32_t>::mulhi`.

**Comment by cyrilbouvier** [comment]
Commit 18f2634 fixes `Simd256<uint32_t>::mulhi`.

I also merge master into the branch to get the fixes from #208.

**Comment by cyrilbouvier** [comment]
The Mac OS machine on Travis is still failing. I think that the reason is that the machine has AVX but not AVX2 (the command line for compiling the tests shows `-mavx` but no `-mavx2`).

The problem is similar to the problem of Pierre with AVX512:
- the file `fflas_simd.h` includes `fflas_simd/simd256.inl` if the machine has AVX or AVX2:
```cpp
#if defined(__FFLASFFPACK_HAVE_AVX_INSTRUCTIONS) or defined(__FFLASFFPACK_HAVE_AVX2_INSTRUCTIONS)
#include "fflas-ffpack/fflas/fflas_simd/simd256.inl"

...

#endif
```

- the file `fflas_simd/simd256.inl` should includes `fflas_simd/simd256_*.inl` that contain the implementation of the specialization of `Simd256_impl`

- but in  `fflas_simd/simd256.inl`, the inclusion of `fflas_simd/simd256_int*.inl` is done only if the machine has AVX2:
```cpp
#if defined(__FFLASFFPACK_HAVE_AVX2_INSTRUCTIONS)
#ifdef __x86_64__
#include "simd256_int64.inl"
#endif
#include "simd256_int32.inl"
#include "simd256_int16.inl"
#endif

#endif //#ifdef SIMD_INT
```
So the specialization are not implemented for integral types for Simd256 when the machine has AVX but not AVX2.




I will try to take this into account in `test-simd.C`.

I think that it is a good example of why we need a simpler mechanism to be able to detect which `Simdnnn_impl` are defined at compile time, in order to be able to write code using SIMD more easily. Otherwise every person adding code with SIMD must know exactly which `#define` must be used for every combination of SIMD intrinsics and base type.

**Comment by ClementPernet** [comment]
Yes, this is exactly a similar problem as for the AVX512.
Note the it is the right decision to not include simd256_int files when only AVX1 is available as there is no 256 wide registers for integers on this micro-arch.
I just pushed a fix for the AVX512 problem on this branch and added some ifdefs in the test-simd to only enable the int32 and int16 cases when no AVX512 is available.
We took this decision with Pierre because we want to cut a fflas-ffpack release very soon and eventhough Pierre will eventually write/fix the int32, int16 AVX512 code, this will be postponed to after the release.
How far do you think you are in fixing the remaining issues in this branch?

**Comment by cyrilbouvier** [comment]
> How far do you think you are in fixing the remaining issues in this branch?

All the issues are fixed. There are still lots of SIMD functions that are not tested (~20) but it could be done after the release.

**Comment by ClementPernet** [comment]
Great. I guess this means that this branch can be merged. Let's go!

**Pull request merged**
