### PR TITLE
[WIP] fix mistakes in PR #197

### PR DESCRIPTION
**Pull request by ClementPernet**
fixing remaining bugs pointed out by @cyrilbouvier  in #197

### CODE REVIEW

**Comment by cyrilbouvier** [comment]
I think there is still one typo, introduced by 534ef0bbc:

```cpp
c1 = Simd256_64::mulx(a1, b1);
c2 = Simd256_64::mulx(a2, b2);			
```

was transformed into

```cpp
c1 = _mm256_mul_epi32(a1, b1);
c2 = _mm256_mul_epi32(a1, b2); 
```

`c2` is computed from **`a1`** instead of **`a2`**

**Comment by ClementPernet** [comment]
good catch. Sorry. I pushed the fix.

**Comment by cyrilbouvier** [comment]
Looks good to me, i don't see other typos.

**Comment by cyrilbouvier** [comment]
I did not find other typo but some simd functions seems buggy. For example `mulhi` for `simd256` on `uint32_t`.
The following code expose the bug:
```cpp
#include "fflas-ffpack/fflas/fflas_simd.h"

int
main (int argc, char *argv[])
{
    typedef Simd256<uint32_t> simd;
    typedef typename simd::vect_t Vect;

    uint32_t a1[] = { 152787465, 166362778, 180663186, 237292620, 157724898,
                      270274496, 172415010, 202247933 };
    uint32_t a2[] = { 46, 1352326542, 718045038, 2346130244, 3464021106,
                      1228844645, 1818948342, 3271010721 };
    uint32_t ar[8];

    Vect v1 = simd::load (a1);
    Vect v2 = simd::load (a2);
    Vect r = simd::mulhi (v1, v2);
    simd::store (ar, r);

    for (unsigned int i = 0; i < 8; i++)
    {
        uint64_t m1 = (uint64_t) a1[i];
        uint64_t m2 = (uint64_t) a2[i];
        uint32_t e = (m1*m2) >> 32;
        if (e == ar[i])
            std::cout << i << ": Ok" << std::endl;
        else
            std::cout << i << ": error, got " << ar[i] << ", expected "
                                              << e << std::endl;
    }
    return 0;
}
```

I got as output (with fflas at the top of the fix_simd64 branch):
```
0: Ok
1: Ok
2: Ok
3: error, got 4187296010, expected 129621334
4: error, got 4264452301, expected 127209903
5: Ok
6: Ok
7: error, got 4246749676, expected 154030313
```

I see that there is a `tests/test-simd.C` file but that it does not compile. I will rewrite it in order to start to test the simd functions. Should I do it in another branch ?

**Comment by ClementPernet** [comment]
Argh.
Yes these SIMD routines should be much better tested. I'm surprised test-simd no longer compiles. It may have happened recently.
Anyway, it should be fixed, added to the main test-suite and its scope should be enlarged.
You failing example could be added to test-regression.C, which is precisely intended to put such bug-revealing code-chunks.
And yes, this should happen in a separate branch.
Thanks for volunteering!

**Comment by cyrilbouvier** [comment]
> Yes these SIMD routines should be much better tested. I'm surprised test-simd no longer compiles. It may have happened recently.
Anyway, it should be fixed, added to the main test-suite and its scope should be enlarged.

I started to do it in #212.

> You failing example could be added to test-regression.C, which is precisely intended to put such bug-revealing code-chunks.

I do not think that is necessary: the rewritten test-simd.C of #212 shows a systematic failure for `mulhi`; the function is broken for all inputs and not only in the case of the small example I exhibited in the previous message (which came from a test of the fft code in linbox). Once the test for `mulhi` will pass, the non regression test would be redundant with `test-simd.C`.


The good news is that so far, `Simd256<uint32_t>::mulhi` is the only failing functions (using test from #212).

**Comment by ClementPernet** [comment]
I'll close this PR as this branch (conflicting with master) is now merged into test_simd from PR #212 . All following discussions should then happen in #212 .

**Pull request closed without merging**
