### PR TITLE
Determinant computation example

### PR DESCRIPTION
**Pull request by Breush**
For #177.

Wanted to be sure the design (based on pluq example) is all right.
If so, I can populate even more.

### CODE REVIEW

**Comment by ClementPernet** [comment]
2 remarks:

- I am wondering whether we should maybe restrict the output to the bare minimum (thinking of someone using it from another program, to avoid parsing too much). Printing the det may be sufficient here, no need for dimensions and text.
- I tried it with several matrices. It works with smallish matrices up to 50x50. But with larger ones (from 100x100) it fails:
```
[pernet@niqually] :~/Logiciels/fflas-ffpack/examples > ./det 65521 A1
Matrix file does not respect the SMS format
Input matrix is 140583997411328x0
posix_memalign error
Det is 0
```

**Comment by Breush** [comment]
@ClementPernet Can you link here a matrix that fails?
Seems like the `ReadMatrix` has some issues with my changes.

**Comment by ClementPernet** [comment]
Here is one 100x100 that fails on my laptop.
[A.sms.gz](https://github.com/linbox-team/fflas-ffpack/files/2434152/A.sms.gz)

**Comment by Breush** [comment]
@ClementPernet Updated. I cleaned-up the output, fixed the `preambule` of `ReadMatrix` and fixed indentation.

**Comment by ClementPernet** [comment]
Looks good now. Merging

**Pull request merged**
