### PR TITLE
Faster fsyr2k

### PR DESCRIPTION
**Pull request by jgdumas**
gains one level of Winograd algorithm
overwrites the unused part of the symmetric C

### CODE REVIEW

**Comment by jgdumas** [comment]
ftrssyr2k is failing for now with the new syr2k

**Comment by jgdumas** [comment]
Now test-ftrssyr2k is ok.
test-fsytrf sometimes fails. unfortunately -s seed might not reproduce it.

**Comment by jgdumas** [comment]
Solves issue #286

**Comment by ClementPernet** [comment]
I've fixed the merge conflict. LGTM.

**Pull request merged**
