### PR TITLE
Unify code style

### PR DESCRIPTION
**Pull request by vneiger**
Hi,
Following the reported issue about inconsistent code style (tabulations, indentation, and editors modelines differed from file to file, cf #204 ), I did the following steps on all files (`.h, .inl, .C`):
- remove existing (inconsistent) modelines
- instead, put at the very last two lines of the files, the following emacs/vim modelines:
```
/* -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
// vim:sts=4:sw=4:ts=4:et:sr:cino=>s,f0,{0,g0,(0,\:0,t0,+0,=s
```
- reflow the text according to these modelines (reindent, change tabulations into spaces)
- remove trailing whitespace at the end of lines, if any.

This results in a lot of modifications in almost all files, although of course no actual change of the content / functionalities was made.

The modelines above could be put somewhere in some kind of README, to ensure people can easily find them and insert them when they create a new file.

Thanks,

     Vincent

### CODE REVIEW

**Comment by ClementPernet** [comment]
Great, thanks.
I one thing though, in many files, there remain a blank line in first position. Could you remove them all, so that the first line is the comment of the block with meta data and licencing info?
Once you're done, I'll try to merge with as few working branches around as possible to minimize risks of merge conflicts. It's gonna be nasty anyway!

**Comment by vneiger** [comment]
Hi Clément,
> one thing though, in many files, there remain a blank line in first position. Could you remove them all, so that the first line is the comment of the block with meta data and licencing info?

Done!

**Comment by ClementPernet** [comment]
Awesome. Thanks. Merging (before other branches get forked).
Next step is fixing LinBox, while your sed and scripts are still hot !

**Comment by vneiger** [comment]
I'm not exactly using scripts, just recording a few macros in vim, going through all files, each time applying the right one by pressing a single key :-)

...

(trying to make you forget the beginning of your sentence)

Ok ok, I'll have a look at LinBox, later this week.

**Pull request merged**
