### PR TITLE
Reader writer

### PR DESCRIPTION
**Pull request by ClementPernet**
Rewrite of the Input/Output routines for FFLAS matrices, addressing issue #1 (at last!).
 * `write_field` becomes `WriteMatrix`
 * `read_field` becomes `ReadMatrix`
 * supports In/out streams and filenames given with strings
 * various format supported: SMS, Dense, Binary for input and output and Math, Maple, SageMath for output
 * add a proper test suite
 * update all current uses of write_field and read_field in the library (even commented out)
 * some related clean-up

### CODE REVIEW

**Comment by david-lucas** [comment]
As discussed, I removed the semicolon at the end of `SageMath` output.

I'm still working on the review, but so far, so good.

BTW, I noticed there are several compiler warnings regarding unused variables while running `make check` (`filestring` in `test-charpoly`, l. 151 and `tmp` in `test-ftrsm`, ll. 57 and 75).
I think it could be fixed here as it's trivial fixes, even if it's not exactly the point of this PR.

David

**Comment by ClementPernet** [comment]
No, don't fix them here: the one in test-charpoly will be gone, as I am about to submit a PR with a lot of edits on charpoly and the one with trsm could be done directlye on master.

**Comment by david-lucas** [comment]
Hello,

Tests passes, and changes look good to me. It's a nice addition to manage data import/export.
Merging.

David

**Comment by ClementPernet** [comment]
Thanks!

**Pull request merged**
