### PR TITLE
Some improvements for ffpack documentation

### PR DESCRIPTION
**Pull request by david-lucas**
This PR contains some improvements for FFPACk documentation: 

- Protected/Private functions have been removed from the Doxygen generated doc.
- Documented functions now have a short description for their input parameters.
- Also contains a few typo fixes.

### CODE REVIEW

**Comment by ClementPernet** [comment]
@bdsaunders : the term leading dimension seems to be the one used in most places in the BLAS documentation when referring to lda, and the acronym is also quite clear about it.
See for instance [https://software.intel.com/en-us/node/520775] . This is indeed also a special type of stride.

**Comment by bdsaunders** [comment]
I agree that this phrase is widely used in blas documentation.  It is
probably the worst sin of that (very largely very excellent) scheme of
explanation.

**Comment by david-lucas** [comment]
Sorry for taking so long to answer.
I made the requested changes by listing the choices for short enums.

David

**Comment by ClementPernet** [comment]
Ping @bdsaunders . If you find that David's changes address all your concerns, then you can positive review it and trigger the merge of this pull request (the green button).

**Comment by bdsaunders** [comment]
Thanks.

**Pull request merged**
