### PR TITLE
Various cleanup and fixes

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by jgdumas** [comment]
I am not sure I agree with the suppression of autogen.sh.
As it is it supports some options,
while the proposition make it just like autogen.status ...

**Comment by fingolfin** [comment]
Which options are you talking about? That it used to run configure automatically? I can add that back, as I did for givaro (see https://github.com/linbox-team/givaro/pull/36). Or something else? Could you tell me what exactly?

And of course I can just drop that commit, if you absolutely hate it.

**Comment by jgdumas** [comment]
Ah ok I did not look at the issue in givaro.
Yes my comment is the same as Clement's: I think I like that options are forwarded to configure.
So the givaro solution is great !

**Comment by fingolfin** [comment]
@jgdumas done

**Pull request merged**
